### ISSUE TITLE
No file downloaded after deploying it on an ubuntu server

### ISSUE THREAD

**Issue by Dopamax** [microlinkhq/youtube-dl-exec#220]
Hello,

The library works fine on local machine, I download all type of videos in many formats mp3 mp4 ...etc

but when deploying the app on a Ubunto 24.04 server, when requesting the download it, dosn't download anything on Ubunto server.

I tried to give all the permissions to the directory of downloads.

Whats is the problem ?

![image](https://github.com/user-attachments/assets/aec4a54f-741b-46a7-a458-5e2196139c2b)

**Comment by Kikobeats** [comment]
Hello according with your words, the problem is not in the library, it's in your server setup.

try to set `DEBUG=youtube-dl-exec*` to see what's happening there.

**Comment by Dopamax** [comment]
@Kikobeats I tried running npm install --DEBUG="youtube-dl-exec*" but Ididn't have more details

**Comment by andrei10k** [comment]
same for me on a aws ubuntu machine. no errors no nothing but no file is downloaded

**Comment by andrei10k** [comment]
i fixed it. my problem was the yt-dlp library couldn't be installed automatically. i had to manually install it on my machine using pip3 install -U yt-dlp. i think it should raise an error about this, i struggled a lot until i found the root of the problem.

**Comment by notmutiny** [comment]
Unfortunately I have the same problem but the above solution doesn't resolve it because `yt-dlp` is already installed... I have posted a new issue here: https://github.com/microlinkhq/youtube-dl-exec/issues/226
